analogdotnow/Analog

apps/web/src/components/calendar-view.tsx, apps/web/src/components/event-calendar/month-view.tsx, packages/api/src/providers/google-calendar.ts, packages/api/src/routers/calendars.ts
=> feat: adds getting events for the frontend

packages/api/src/providers/google-calendar.ts, packages/api/src/providers/microsoft-calendar.ts, packages/api/src/providers/utils.ts
=> feat(api): add error handler to providers

packages/api/src/providers/microsoft-calendar/utils.ts
=> fix(api): resolve microsoft graph api error due to missing timezone

apps/web/src/components/calendar-view.tsx
=> fix(web): resolve events outside of default date range not loaded

apps/web/src/components/ui/theme-toggle.tsx
This MR add cursor-pointer css property to ThemeToggle button to match styles with rest of header buttons.
https://github.com/user-attachments/assets/0c446290-227b-4b6a-b2f3-e835b2388b1f
=> chore(web): use pointer cursor for toggle theme button

CONTRIBUTING.md, README.md
=> chore(docs): add microsoft oauth setup instructions to CONTRIBUTING.md and README.md

CONTRIBUTING.md, README.md
=> chore(docs): update google oauth instructions for setting up test users

apps/web/src/components/nav-user.tsx
=> chore(web): add theme picker to user menu

apps/web/src/components/event-calendar/event-dialog.tsx, apps/web/src/components/event-calendar/hooks/use-calendar-actions.ts, apps/web/src/components/event-calendar/hooks/use-event-dialog.ts, apps/web/src/components/event-form/support/event-utils.ts, packages/api/src/providers/google-calendar.ts, packages/api/src/providers/google-calendar/utils.ts, packages/api/src/providers/interfaces.ts, packages/api/src/providers/microsoft-calendar.ts, packages/api/src/providers/microsoft-calendar/utils.ts, packages/api/src/routers/events.ts
=> feat(api): add read only field to calendars and events

apps/web/src/components/event-calendar/draggable-event.tsx, apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/week-view.tsx
=> fix(web): resolve dragging z-index issues day and week views

apps/web/src/components/event-calendar/hooks/use-calendar-actions.ts, apps/web/src/components/event-calendar/hooks/use-event-operations.ts, apps/web/src/components/event-form/event-form.tsx, apps/web/src/components/event-form/utils.ts, apps/web/src/components/right-sidebar.tsx, apps/web/src/lib/utils/calendar.ts, packages/api/src/routers/events.ts, packages/api/src/schemas/events.ts
=> fix(web): resolve duplicate event creation due to race condition

apps/web/src/components/event-calendar/draggable-event.tsx, apps/web/src/components/event-calendar/droppable-cell.tsx, apps/web/src/components/event-calendar/event-item.tsx, apps/web/src/components/event-calendar/hooks/index.ts, apps/web/src/components/event-calendar/hooks/use-grid-layout.ts, apps/web/src/components/event-calendar/hooks/use-multi-day-overflow.ts, apps/web/src/components/event-calendar/index.ts, apps/web/src/components/event-calendar/overflow-indicator.tsx, apps/web/src/components/event-calendar/utils/index.ts, apps/web/src/components/event-calendar/utils/multi-day-layout.ts, apps/web/src/components/event-calendar/views/month-view.tsx, apps/web/src/components/event-calendar/views/week-view.tsx
=> feat(web): add month view position algorithm and improve multi day events (#173)

apps/web/src/components/calendar-layout.tsx, apps/web/src/components/event-form/event-form.tsx, apps/web/src/components/event-form/utils.ts, apps/web/src/components/right-sidebar.tsx, apps/web/src/components/settings-dialog/tabs/accounts.tsx, packages/api/src/routers/accounts.ts, packages/api/src/routers/calendars.ts
=> fix(web): resolve error due to missing default calendar

apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/month-view.tsx, apps/web/src/components/event-calendar/views/week-view.tsx, packages/temporal/src/convert.ts
=> chore(web): adjust calendar views to start of week and time format

apps/web/package.json, apps/web/src/components/calendar-layout.tsx, apps/web/src/components/calendar-view.tsx, apps/web/src/components/event-calendar/draggable-event.tsx, apps/web/src/components/event-calendar/event-context-menu.tsx, apps/web/src/components/event-calendar/event-item.tsx, apps/web/src/components/event-calendar/hooks/use-event-operations.ts, apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/month-view.tsx, apps/web/src/components/event-calendar/views/week-view.tsx, apps/web/src/components/event-context-menu.tsx, apps/web/src/components/ui/context-menu.tsx, apps/web/src/components/ui/toggle-group.tsx, bun.lock
=> feat(web): add event context menu

apps/web/src/atoms/calendar-settings.ts, apps/web/src/components/calendar-layout.tsx, apps/web/src/components/event-calendar/event-item.tsx
=> fix(web): resolve default time zone not being set correctly

apps/web/src/app/(auth)/login/page.tsx, apps/web/src/app/(auth)/login/sign-in-form.tsx, apps/web/src/components/nav-user.tsx
=> chore(web): remove microsoft from sign in page

apps/web/src/components/date-input.tsx, apps/web/src/components/time-input.tsx
=> fix(web): resolve issues time and date fields 

apps/web/src/components/event-calendar/draggable-event.tsx, apps/web/src/components/event-calendar/event-item.tsx, apps/web/src/components/event-calendar/utils/event.ts, apps/web/src/components/time-input.tsx
=> feat(web): improve appearance and overlap calculation small events

apps/web/package.json, package.json, packages/api/package.json, packages/auth/package.json, packages/db/package.json, packages/env/package.json, packages/temporal/package.json, turbo.json
=> chore(repo): add type-check command

.github/workflows/check-types.yaml, .github/workflows/lint.yaml, .gitignore, apps/web/next-env.d.ts
=> chore(ci): add type check github action

apps/web/src/components/event-calendar/event-context-menu.tsx
=> fix(web): resolve incorrect hover color in event context menu

apps/web/src/components/event-form/event-form.tsx, bun.lock
=> fix(web): prevent form submission of unmodified events

apps/web/src/components/event-calendar/calendar-header.tsx, apps/web/src/components/event-calendar/calendar-navigation.tsx, apps/web/src/components/event-calendar/calendar-view-menu.tsx, apps/web/src/components/event-calendar/calendar-view-title.tsx
=> feat(web): improve calendar header responsiveness

apps/web/src/app/globals.css, apps/web/src/app/layout.tsx
=> chore(web): improve font rendering on windows

apps/web/src/app/(landing)/privacy/page.tsx, apps/web/src/app/(landing)/terms/page.tsx, apps/web/src/components/header.tsx, apps/web/src/components/landing-page/legal/text.tsx
=> feat(web): add privacy policy and terms of service

apps/web/src/components/calendar-view.tsx, apps/web/src/components/event-calendar/hooks/use-current-time-indicator.ts, apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/time-indicator.tsx, apps/web/src/components/event-calendar/views/timeline.tsx, apps/web/src/components/event-calendar/views/week-view.tsx
=> feat(web): add new time indicator to calendar view

apps/web/src/components/event-calendar/hooks/use-drag-to-create.tsx, apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/event/drag-preview.tsx, apps/web/src/components/event-calendar/views/week-view.tsx
=> feat(web): add support for drag to create event

apps/web/src/components/event-calendar/hooks/use-events.ts, packages/api/src/providers/interfaces.ts, packages/api/src/providers/microsoft-calendar.ts, packages/api/src/routers/events.ts
=> fix(api): resolve outlook calendar always displayed in UTC

apps/web/package.json, bun.lock
=> fix(deps): upgrade next.js to resolve windows issue

apps/web/src/components/event-form/date-input-section.tsx, apps/web/src/components/time-input.tsx
Combo box bug fixed which opens start time and end time at one(#233)
https://github.com/user-attachments/assets/a8b863df-6673-4491-a30f-095d5daabca4
=> fix(web): prevent time comboboxes from being open simultaneously (#233)

apps/web/src/components/event-calendar/views/month-view.tsx
=> fix(web): remove double border in month view

apps/web/src/atoms/drag-resize-state.ts, apps/web/src/atoms/index.ts, apps/web/src/components/calendar-view.tsx, apps/web/src/components/event-calendar/drag-and-drop/use-auto-scroll.tsx, apps/web/src/components/event-calendar/draggable-event.tsx, apps/web/src/components/event-calendar/hooks/use-drag-to-create.tsx, apps/web/src/components/event-calendar/views/day-view.tsx, apps/web/src/components/event-calendar/views/month-view.tsx, apps/web/src/components/event-calendar/views/time-indicator.tsx, apps/web/src/components/event-calendar/views/timeline.tsx, apps/web/src/components/event-calendar/views/week-view.tsx
=> feat(web): add auto scroll at edge during drag and resize

apps/web/src/lib/providers.ts
=> fix(web): resolve incorrect provider names

apps/web/src/app/api/trpc/[trpc]/route.ts, apps/web/src/lib/trpc/client.tsx
=> feat(api): use http post requests for trpc

packages/api/src/trpc.ts, packages/api/src/utils/redis.ts
=> feat(api): add tRPC rate limiting middleware

apps/web/src/components/calendar/event/event-context-menu.tsx, apps/web/src/components/nav-user.tsx, apps/web/src/components/ui/context-menu.tsx
=> fix(web): resolve minor ui inconsistencies 

apps/web/src/components/event-form/recurrences/recurrence-dialog.tsx, apps/web/src/components/event-form/recurrences/recurrence-field.tsx
=> fix(web): resolve incorrect frequency values in recurrence dialog

apps/web/src/components/calendar/event/event-context-menu.tsx, apps/web/src/components/calendar/hooks/use-events.ts, apps/web/src/components/calendar/hooks/use-optimistic-events.ts, apps/web/src/components/calendar/utils/move.ts, apps/web/src/components/event-form/calendar-list-picker.tsx, apps/web/src/components/event-form/event-form.tsx, packages/api/src/providers/calendars/google-calendar.ts, packages/api/src/providers/calendars/interfaces.ts, packages/api/src/providers/calendars/microsoft-calendar.ts, packages/api/src/routers/events.ts, packages/api/src/utils/index.ts
=> feat(api): add support for moving events between calendars

apps/web/src/components/event-form/attendees/attendee-list-input.tsx, apps/web/src/components/event-form/event-form.tsx, apps/web/src/lib/utils/events.ts
=> fix(web): resolve form submission issues

apps/web/src/components/nav-user.tsx, apps/web/src/components/settings-dialog/settings-dialog.tsx
=> chore(web): implement new settings dialog design

apps/web/src/atoms/calendar-settings.ts
https://analog-interface.sentry.io/issues/58502063/events/715d60acb5ee45d38e59a4ef67a746b7/
=> fix(web): resolve invalid time zone issue in safari

apps/web/src/components/calendar/event/draggable-event.tsx
=> fix(web): resolve flickering when dragging or resizing

packages/api/src/providers/calendars/google-calendar.ts
=> fix(api): resolve conflict during event creation

apps/web/src/components/calendar/flows/create-event/use-create-action.tsx, apps/web/src/components/event-form/event-form.tsx
Removed duplicate actions for drafts. Events that were created from drafts can now be renamed, moved, etc.
fixes #326 
=> fix(web): clear draft optimistic action when creating event
